'use client';

/*
  Auto-generated by Spline — Jozi Bakes shop diorama with Jozi & Bruno.
  Additions on top of the export: responsive orthographic zoom (the export
  ships without one, so the diorama would render tiny), and gentle idle
  "breathing" animation on the Jozi / Bruno / shop-title groups.
*/
import { useMemo, useRef } from 'react';
import useSpline from '@splinetool/r3f-spline';
import { OrthographicCamera } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import type { Group, Mesh } from 'three';

/** Approximate world-unit footprint of the composition (shop + trees). */
const SCENE_WIDTH = 300;
const SCENE_HEIGHT = 240;

export default function Scene({
  reducedMotion = false,
  ...props
}: { reducedMotion?: boolean } & Record<string, unknown>) {
  const { nodes, materials } = useSpline(
    'https://prod.spline.design/Le2iIYYasafjz8Ib/scene.splinecode',
  );

  const { size } = useThree();

  // Fit the diorama to the viewport: near full-width on portrait phones,
  // height-bound on landscape/desktop so the type above never collides.
  // cameraY nudges the composition up toward the headline (higher world
  // point at screen center = diorama sits higher in the frame).
  const { zoom, cameraY } = useMemo(() => {
    const portrait = size.height > size.width;
    const short = !portrait && size.height < 540; // phone rotated sideways
    const widthZoom = (size.width * (portrait ? 0.97 : 0.8)) / SCENE_WIDTH;
    const heightZoom =
      (size.height * (portrait ? 0.52 : short ? 0.52 : 0.62)) / SCENE_HEIGHT;
    return {
      zoom: Math.min(widthZoom, heightZoom),
      cameraY: portrait ? 112 : short ? 96 : 128,
    };
  }, [size.width, size.height]);

  const joziRef = useRef<Group>(null);
  const brunoRef = useRef<Group>(null);
  const titleRef = useRef<Mesh>(null);

  useFrame(({ clock }) => {
    if (reducedMotion) return;
    const t = clock.getElapsedTime();
    if (joziRef.current) {
      // soft breathing — barely-there vertical stretch
      joziRef.current.scale.y = 50 * (1 + Math.sin(t * 1.7) * 0.006);
      joziRef.current.scale.x = 50 * (1 - Math.sin(t * 1.7) * 0.003);
      joziRef.current.scale.z = 50 * (1 - Math.sin(t * 1.7) * 0.003);
    }
    if (brunoRef.current) {
      // curious idle sway + tiny excited bounce
      brunoRef.current.rotation.y = 1.15 + Math.sin(t * 0.8) * 0.06;
      brunoRef.current.position.y = 23.33 + Math.abs(Math.sin(t * 2.4)) * 1.1;
    }
    if (titleRef.current) {
      // the hanging sign floats, almost imperceptibly
      titleRef.current.position.y = 76.85 + Math.sin(t * 0.9) * 0.5;
    }
  });

  return (
    <>
      <group {...props} dispose={null}>
        <scene name="Main">
          <OrthographicCamera
            name="Camera"
            makeDefault={true}
            zoom={zoom}
            far={100000}
            near={-100000}
            position={[0, cameraY, 1000]}
          />
          <directionalLight
            name="Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[200, 420.52, 300]}
          />
          <group ref={joziRef} name="Jozi" position={[0, 23.86, 81.63]} scale={50}>
            <group name="JoziRig">
              <skinnedMesh
                name="Body"
                geometry={nodes.Body.geometry}
                material={nodes.Body.material}
                skeleton={nodes.Body.skeleton}
                castShadow
                receiveShadow
              />
              <skinnedMesh
                name="Coat"
                geometry={nodes.Coat.geometry}
                material={nodes.Coat.material}
                skeleton={nodes.Coat.skeleton}
                castShadow
                receiveShadow
              />
              <skinnedMesh
                name="Hair"
                geometry={nodes.Hair.geometry}
                material={nodes.Hair.material}
                skeleton={nodes.Hair.skeleton}
                castShadow
                receiveShadow
              />
              <skinnedMesh
                name="Hat"
                geometry={nodes.Hat.geometry}
                material={nodes.Hat.material}
                skeleton={nodes.Hat.skeleton}
                castShadow
                receiveShadow
              />
              <skinnedMesh
                name="Pants"
                geometry={nodes.Pants.geometry}
                material={nodes.Pants.material}
                skeleton={nodes.Pants.skeleton}
                castShadow
                receiveShadow
              />
              <skinnedMesh
                name="Shoes"
                geometry={nodes.Shoes.geometry}
                material={nodes.Shoes.material}
                skeleton={nodes.Shoes.skeleton}
                castShadow
                receiveShadow
              />
              <primitive object={nodes.root} />
            </group>
          </group>
          <group
            ref={brunoRef}
            name="Bruno"
            position={[25.04, 23.33, 81.15]}
            rotation={[0, 1.15, 0]}
            scale={42.27}
          >
            <group name="BrunoRig">
              <skinnedMesh
                name="Dog"
                geometry={nodes.Dog.geometry}
                material={nodes.Dog.material}
                skeleton={nodes.Dog.skeleton}
                castShadow
                receiveShadow
              />
              <primitive object={nodes.root1} />
            </group>
          </group>
          <group name="Shop" position={[0, 16.44, 0]} scale={1.7}>
            <mesh
              ref={titleRef}
              name="ShopTitle"
              geometry={nodes.ShopTitle.geometry}
              material={materials['ShopTitle Material']}
              castShadow
              receiveShadow
              position={[-5.09, 76.85, 22.55]}
              scale={0.47}
            />
            <mesh
              name="ShopMesh"
              geometry={nodes.ShopMesh.geometry}
              material={nodes.ShopMesh.material}
              castShadow
              receiveShadow
              rotation={[Math.PI / 2, 0, 0]}
            />
          </group>
          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} />
        </scene>
      </group>
    </>
  );
}
