/*
  Auto-generated by Spline
*/
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }: any) {
  const { nodes, materials } = useSpline('https://prod.spline.design/Le2iIYYasafjz8Ib/scene.splinecode')

  return (
    <>
      <color attach="background" args={['#fbf5e5']} />
      <group {...props} dispose={null}>
        <scene name="Main">
          <OrthographicCamera name="Camera" makeDefault={true} far={100000} near={-100000} position={[0, 143, 1000]} />
          <directionalLight
            name="Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[200, 420.52, 300]}
          />
          <group name="Jozi" position={[0, 23.86, 81.63]} scale={50}>
            <group name="JoziRig">
              <mesh
                name="Body"
                geometry={nodes.Body.geometry}
                material={nodes.Body.material}
                skeleton={nodes.Body.skeleton}
                castShadow
                receiveShadow
              />
              <mesh
                name="Coat"
                geometry={nodes.Coat.geometry}
                material={nodes.Coat.material}
                skeleton={nodes.Coat.skeleton}
                castShadow
                receiveShadow
              />
              <mesh
                name="Hair"
                geometry={nodes.Hair.geometry}
                material={nodes.Hair.material}
                skeleton={nodes.Hair.skeleton}
                castShadow
                receiveShadow
              />
              <mesh
                name="Hat"
                geometry={nodes.Hat.geometry}
                material={nodes.Hat.material}
                skeleton={nodes.Hat.skeleton}
                castShadow
                receiveShadow
              />
              <mesh
                name="Pants"
                geometry={nodes.Pants.geometry}
                material={nodes.Pants.material}
                skeleton={nodes.Pants.skeleton}
                castShadow
                receiveShadow
              />
              <mesh
                name="Shoes"
                geometry={nodes.Shoes.geometry}
                material={nodes.Shoes.material}
                skeleton={nodes.Shoes.skeleton}
                castShadow
                receiveShadow
              />
              <primitive object={nodes.root} />
            </group>
          </group>
          <group name="Bruno" position={[25.04, 23.33, 81.15]} rotation={[0, 1.15, 0]} scale={42.27}>
            <group name="BrunoRig">
              <mesh
                name="Dog"
                geometry={nodes.Dog.geometry}
                material={nodes.Dog.material}
                skeleton={nodes.Dog.skeleton}
                castShadow
                receiveShadow
              />
              <primitive object={nodes.root1} />
            </group>
          </group>
          <group name="Shop" position={[0, 16.44, 0]} scale={1.7}>
            <mesh
              name="ShopTitle"
              geometry={nodes.ShopTitle.geometry}
              material={materials['ShopTitle Material']}
              castShadow
              receiveShadow
              position={[-5.09, 76.85, 22.55]}
              scale={0.47}
            />
            <mesh
              name="ShopMesh"
              geometry={nodes.ShopMesh.geometry}
              material={nodes.ShopMesh.material}
              castShadow
              receiveShadow
              rotation={[Math.PI / 2, 0, 0]}
            />
          </group>
          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} />
        </scene>
      </group>
    </>
  )
}
